[package]
name = "common"
description = "Common types and functions"
version = "0.1.0"
license = "Apache-2.0"
edition = "2021"

[lib]
doctest = false

[dependencies]
bitcoin = { version = "0.31.1", features = ["default", "bitcoinconsensus-std"] }
thiserror = { version = "1.0.58" }
